{
 "title": "Test",
 "tags": [ "templated" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": ".*" },
   {
    "name": "job",
    "query": {
     "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prometheus_build_info,pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job_2",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node_2",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "instance_2",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"(?i:($node))\"},instance)"
    }
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   },
   {
    "name": "namespace_2",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "created_by",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", container!=\"\"},created_by_name)"
    }
   },
   {
    "name": "pod_2",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"POD\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "TCP Currently Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance_2\"}",
     "legendFormat": "TCP Currently Established"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance_2\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$instance_2\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$instance_2\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance_2\"} - node_memory_MemFree_bytes{instance=\"$instance_2\"} - (node_memory_Cached_bytes{instance=\"$instance_2\"} + node_memory_Buffers_bytes{instance=\"$instance_2\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance_2\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance_2\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance_2\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance_2\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance_@\"} - node_memory_SwapFree_bytes{instance=\"$instance_2\"}",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance_2\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  {
   "title": "List of pods on node ($node)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$node_2\"}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance_2\"} - node_boot_time_seconds{instance=\"$instance_2\"}"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$node_2\"})"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$instance_2\"} - node_memory_MemAvailable_bytes{instance=\"$instance_2\"}) / sum(node_memory_MemTotal_bytes{instance=\"$instance_2\"})"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype!=\"tmpfs\"}) by (node)/1024"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod, container)"
    }
   ]
  },
  {
   "title": "GC Rate / 2m",
   "type": "graph",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" },
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "Chunks" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime [$interval]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 11, "x": 6, "y": 100 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "Amount of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node_2) (kube_node_info))"
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "gauge",
   "description": "Total amount of CPU used",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / sum(rate(node_cpu_seconds_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "description": "Total RAM used in node.",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes)) / 1024 / 1024 "
    }
   ]
  },
  {
   "title": "Amount of Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  }
 ]
}